routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('/file/{filename}', 'FileController@getFile')->where('filename', '^(.+)\/([^\/]+)$')->name('getFile');

Auth::routes();

Route::namespace('Admin')->prefix('admin')->as('admin.')->middleware('auth')->middleware('role:super-admin')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::post('/lessons/publish', 'LessonController@publish')->name('lessons.publish');
    Route::post('/lessons/suspend', 'LessonController@suspend')->name('lessons.suspend');
    Route::get('/lessons/preview/{id}', 'LessonController@preview')->name('lessons.preview');
    Route::resource('/lessons', 'LessonController');

    Route::post('/schools/activate', 'SchoolController@activate')->name('schools.activate');
    Route::post('/schools/suspend', 'SchoolController@suspend')->name('schools.suspend');
    Route::post('/schools/archive', 'SchoolController@archive')->name('schools.archive');
    Route::post('/schools/reinstate', 'SchoolController@reinstate')->name('schools.reinstate');
    Route::get('/schools/showArchived', 'SchoolController@showArchived')->name('schools.showArchived');
    Route::post('/schools/setExpiryDate', 'SchoolController@setExpiryDate')->name('schools.setExpiryDate');
    Route::get('/schools/viewInvoice/{schoolID}', 'SchoolController@viewInvoice')->name('schools.viewInvoice');
    Route::resource('/schools', 'SchoolController');

    Route::post('/invoices/paid', 'InvoiceController@paid')->name('invoices.paid');
    Route::post('/invoices/send', 'InvoiceController@send')->name('invoices.send');
    Route::post('/invoices/cancel', 'InvoiceController@cancel')->name('invoices.cancel');
    Route::get('/invoices/showArchived', 'InvoiceController@showArchived')->name('invoices.showArchived');
    Route::get('/invoices/download/{invoice}', 'InvoiceController@download')->name('invoices.download');
    Route::get('/invoices/sendReminder/{invoice}', 'InvoiceController@sendReminder')->name('invoices.sendReminder');
    Route::post('/invoices/downloadXeroInvoice', 'InvoiceController@downloadXeroInvoice')->name('invoices.downloadXeroInvoice');
    Route::post('/invoices/adhocStore', 'InvoiceController@adhocStore')->name('invoices.adhocStore');
    Route::resource('/invoices', 'InvoiceController');
    

    Route::get('/resources/files', 'ResourceController@listFiles')->name('resources.listFiles');
    Route::get('/resources/images', 'ResourceController@listImages')->name('resources.listImages');
    Route::resource('/resources', 'ResourceController');

    Route::post('/users/activate', 'UserController@activate')->name('users.activate');
    Route::post('/users/suspend', 'UserController@suspend')->name('users.suspend');
    Route::post('/users/archive', 'UserController@archive')->name('users.archive');
    Route::post('/users/reinstate', 'UserController@reinstate')->name('users.reinstate');
    Route::get('/users/showArchived', 'UserController@showArchived')->name('users.showArchived');
    Route::post('/users/sendResetLinkEmail', 'UserController@sendResetLinkEmail')->name('users.sendResetLinkEmail');
    Route::post('/users/sendResetPassEmail', 'UserController@sendResetPassEmail')->name('users.sendResetPassEmail');
    Route::get('/users/changePassReq', 'UserController@changePassReq')->name('users.changePassReq');
    Route::post('/users/changePassword', 'UserController@changePassword')->name('users.changePassword');
    Route::resource('/users', 'UserController');

    Route::get('/reports/users', 'ReportsController@userindex')->name('reports.userindex');
    Route::get('/reports/schools', 'ReportsController@schoolindex')->name('reports.schoolindex');
    Route::get('/reports/invoices', 'ReportsController@invoiceindex')->name('reports.invoiceindex');
    Route::post('/reports/getusers', 'ReportsController@getusers')->name('reports.getusers');
    Route::post('/reports/getschools', 'ReportsController@getschools')->name('reports.getschools');
    Route::post('/reports/getinvoices', 'ReportsController@getinvoices')->name('reports.getinvoices');
    /* 
 * We name this route xero.auth.success as by default the config looks for a route with this name to redirect back to
 * after authentication has succeeded. The name of this route can be changed in the config file.
 */
    Route::get('/manage/xero', 'XeroController@index')->name('xero.auth.success');

    Route::post('/forums/open', 'ForumController@open')->name('forums.open');
    Route::post('/forums/close', 'ForumController@close')->name('forums.close');
    Route::resource('/forums', 'ForumController');

    Route::post('/topics/open', 'TopicController@open')->name('topics.open');
    Route::post('/topics/close', 'TopicController@close')->name('topics.close');
    Route::resource('/topics', 'TopicController');

    Route::resource('/replies', 'ReplyController');

    Route::resource('/yearlevels', 'YearLevelController');
    Route::resource('/contentstrands', 'ContentStrandController');
    Route::resource('/pedagogies', 'PedagogyController');
    Route::resource('/curricula', 'CurriculumController');
    Route::resource('/schooltypes', 'SchoolTypeController');
    Route::resource('/schoolsectors', 'SchoolSectorController');
    Route::resource('/schoolsizestudents', 'SchoolSizeStudentController');
    Route::resource('/schoolsizeteachers', 'SchoolSizeTeacherController');
    Route::get('/subscriptionplans/select/{school_size_id}', 'SubscriptionPlanController@select')->name('subscriptionplans.select');
    Route::resource('/subscriptionplans', 'SubscriptionPlanController');
    Route::resource('/countries', 'CountryController');
    Route::resource('/locations', 'LocationController');
    Route::resource('/discounts', 'DiscountController');

    Route::resource('/subscriptionpage', 'SubscriptionPageController');
    Route::resource('/aboutpage', 'AboutPageController');

    Route::post('/advertisements/publish', 'AdvertisementController@publish')->name('advertisements.publish');
    Route::post('/advertisements/suspend', 'AdvertisementController@suspend')->name('advertisements.suspend');
    Route::resource('/advertisements', 'AdvertisementController');

    Route::resource('/settings', 'SettingController');
    Route::resource('/faqpage', 'FAQPageController');
    //for tags
    Route::resource('/tags', 'TagController');
});

Route::namespace('Front')->as('front.')->group(function () {
    Route::get('/lessons/sample/{id}', 'LessonController@sample')->name('lessons.sample');
    Route::get('/lessons/listall', 'LessonController@listall')->name('lessons.listall');
    Route::post('/lessons/setAccessCode', 'LessonController@setAccessCode')->name('lessons.setAccessCode');

    Route::resource('/lessons', 'LessonController');
    //Route::resource('/faq', 'FAQController');
    Route::resource('/forums', 'ForumController');
    Route::resource('/topics', 'TopicController');
    Route::resource('/replies', 'ReplyController');
    Route::resource('/ads', 'AdvertisementController');

    Route::get('/contact', 'ContactController@index');
    Route::get('/about', 'AboutPageController@index')->name('about');
    Route::get('/subscribe', 'SubscriptionPageController@index')->name('subscription.index');
    Route::get('/terms/{hasAction}', 'SubscriptionPageController@termsAndConditions')->name('subscription.termsAndConditions');
    Route::get('/subscribe/create', 'SubscriptionPageController@create')->name('subscription.create');
    Route::post('/subscribe/store', 'SubscriptionPageController@store')->name('subscription.store');
    Route::get('/subscribe/notice', 'SubscriptionPageController@notice')->name('subscription.notice');
    Route::get('/subscribe/select/{school_size_id}', 'SubscriptionPageController@select')->name('subscription.select');

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/faq', 'FAQPageController@index')->name('faq');


    Route::post('/users/activate', 'UserController@activate')->name('users.activate');
    Route::post('/users/suspend', 'UserController@suspend')->name('users.suspend');
    Route::post('/users/archive', 'UserController@archive')->name('users.archive');
    Route::post('/users/reinstate', 'UserController@reinstate')->name('users.reinstate');
    Route::get('/users/showArchived', 'UserController@showArchived')->name('users.showArchived');
    Route::post('/users/sendResetLinkEmail', 'UserController@sendResetLinkEmail')->name('users.sendResetLinkEmail');
    Route::post('/users/sendResetPassEmail', 'UserController@sendResetPassEmail')->name('users.sendResetPassEmail');
    Route::get('/users/changePassReq', 'UserController@changePassReq')->name('users.changePassReq');
    Route::post('/users/changePassword', 'UserController@changePassword')->name('users.changePassword');
    Route::post('/users/addfavlesson', 'UserController@addfavlesson')->name('users.addfavlesson');
    Route::post('/users/removefavlesson', 'UserController@removefavlesson')->name('users.removefavlesson');
    Route::get('/users/listfavlessons', 'UserController@listfavlessons')->name('users.listfavlessons');
    Route::get('/users/invoices', 'UserController@invoices')->name('users.invoices');
    Route::get('/users/showInvoice/{invoice}', 'UserController@showInvoice')->name('users.showInvoice');
    Route::get('/users/downloadInvoice/{invoice}', 'UserController@downloadInvoice')->name('users.downloadInvoice');
    Route::resource('/users', 'UserController');
});

app/Http/Controllers/Admin/ForumController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ForumRequest;
use App\Models\Forum;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class ForumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = Forum::query();

        if ($request->has('q') && $request->q != null) {
            // record user input keywords for further analysis in the future
            Log::info("search_keyword: " . $request->q);
            $query->keyWords($request->q);
        }

        $arr['forums'] = $query->get();

        // allow using Input::old() function in view to access the data.
        $request->flash();

        return view('admin.forums.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.forums.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\ForumRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ForumRequest $request)
    {
        // Retrieve the validated input data...
        $validated = $request->validated();
        $forum = new Forum();
        $forum->title = $validated['title'];
        if(!empty($validated['description'])) {
            $forum->description = $validated['description'];
        }
        $forum->sticky = $validated['sticky'];
        $forum->visibility = $validated['visibility'];
        $forum->save();

        Log::info("create forum " . $forum->id);

        $request->session()->flash('alert-success', 'Forum added successfully.');

        return redirect()->route('admin.forums.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function show(Forum $forum)
    {
        $arr['forum'] = $forum;

        return view('admin.forums.show')->with($arr);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function edit(Forum $forum)
    {
        $arr['forum'] = $forum;

        return view('admin.forums.edit')->with($arr);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\ForumRequest  $request
     * @param  \App\Models\Forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function update(ForumRequest $request, Forum $forum)
    {
        // Retrieve the validated input data...
        $validated = $request->validated();
        $forum->title = $validated['title'];
        if(!empty($validated['description'])) {
            $forum->description = $validated['description'];
        }
        $forum->sticky = $validated['sticky'];
        $forum->visibility = $validated['visibility'];
        $forum->save();

        Log::info("update forum " . $forum->id);

        $request->session()->flash('alert-success', 'Forum updated successfully.');

        return redirect()->route('admin.forums.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $forum = Forum::findOrFail($id);
        Log::info("delete forum " . $id);

        /**
         * Note: all topics/replies related will be deleted cascade
         */
        $forum->delete();

        return response()->json($forum);
    }

    /**
     * Change status to opened.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function open(Request $request)
    {
        $id = $request->id_open;

        $forum = Forum::findOrFail($id);
        Log::info("open forum " . $id);

        $forum->status = 1;
        $forum->save();

        $request->session()->flash('alert-success', 'Forum opened successfully.');

        return redirect()->route('admin.forums.index');
    }

    /**
     * Change status to closed.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function close(Request $request)
    {
        $id = $request->id_close;

        $forum = Forum::findOrFail($id);
        Log::info("close forum " . $id);

        $forum->status = 0;
        $forum->save();

        $request->session()->flash('alert-success', 'Forum closed successfully.');

        return redirect()->route('admin.forums.index');
    }
}

app/Http/Controllers/Front/ForumController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Models\Forum;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class ForumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = Forum::query();

        if ($request->has('q') && $request->q != null) {
            // record user input keywords for further analysis in the future
            Log::info("search_keyword: " . $request->q);
            $query->keyWords($request->q);
        }

        // show forums with visibility of public
        $query->visibility(1);
        // show forums with sticky 1 first
        $query->orderBy('sticky', 'desc');
        $query->orderBy('id', 'asc');

        $arr['forums'] = $query->paginate(10);

        // allow using Input::old() function in view to access the data.
        $request->flash();
        return view('front.forums.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function show(Forum $forum)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function edit(Forum $forum)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Forum $forum)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function destroy(Forum $forum)
    {
        //
    }
}

resources/views/admin/forums/create.blade.php
@extends('adminlte::page')

@push('css')
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset ('vendor/adminlte/vendor/select2/dist/css/select2.min.css')}}">
@endpush

@section('title', 'Maths 300')

@section('content_header')
    <h1>
        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="{{ route('admin.forums.index') }}">Forums</a></li>
    </ol>
@stop

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Add forum</h3>
        </div>
        <!-- /.box-header -->

        <div class="box-body">
            @if(count($errors))
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.
                    <br/>
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
        @endif
        <!-- form start -->
            <form id="forumForm" role="form" method="post" action="{{ route('admin.forums.store') }}">
                {{ csrf_field() }}
                <div class="box-body">
                    <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" id="title" name="title"
                               value="{{ old('title') }}">
                        <span class="text-danger">{{ $errors->first('title') }}</span>
                    </div>

                    <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                        <label for="description">Description</label>
                        <textarea class="form-control " id="description"
                                  name="description" rows="3">{{ old('description') }}</textarea>
                        <span class="text-danger">{{ $errors->first('description') }}</span>
                    </div>

                    <div class="form-group {{ $errors->has('sticky') ? 'has-error' : '' }}">
                        <label for="sticky">Sticky</label><br>
                        <div>
                            <input class="minimal" type="radio" id="sticky_yes"
                                   name="sticky"
                                   value="1" {{ old('sticky') == '1' ? 'checked' : '' }}>
                            <label for="sticky_yes">Yes</label>&nbsp;&nbsp;

                            <input class="minimal" type="radio" id="sticky_no"
                                   name="sticky"
                                   value="0" {{ old('sticky', 0) == '0' ? 'checked' : '' }}>
                            <label for="sticky_no">No</label>
                        </div>
                        <span class="text-danger">{{ $errors->first('sticky') }}</span>
                    </div>

                    <div class="form-group {{ $errors->has('visibility') ? 'has-error' : '' }}">
                        <label for="visibility">Visibility</label><br>
                        <div>
                            <input class="minimal" type="radio" id="visibility_yes"
                                   name="visibility"
                                   value="1" {{ old('visibility',1) == '1' ? 'checked' : '' }}>
                            <label for="visibility_yes">Yes</label>&nbsp;&nbsp;

                            <input class="minimal" type="radio" id="visibility_no"
                                   name="visibility"
                                   value="0" {{ old('visibility') == '0' ? 'checked' : '' }}>
                            <label for="visibility_no">No</label>
                        </div>
                        <span class="text-danger">{{ $errors->first('visibility') }}</span>
                    </div>

                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary ladda-button" data-style="expand-right"><span
                                class="ladda-label">Submit</span></button>
                </div>
            </form>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@stop

@push('js')
    <!-- Select2 -->
    <script src="{{ asset ('vendor/adminlte/vendor/select2/dist/js/select2.full.min.js')}}"></script>
    <!-- icheck checkboxes -->
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script>
        $(document).ready(function () {
            // Automatically trigger the loading animation on click
            Ladda.bind('button[type=submit]');
        });
    </script>
@endpush

resources/views/admin/forums/index.blade.php
@extends('adminlte::page')

@push('css')
    <!-- DataTables -->
    <link rel="stylesheet"
          href="{{ asset('vendor/adminlte/vendor/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset ('vendor/adminlte/vendor/select2/dist/css/select2.min.css')}}">

    <style>
        table.dataTable tbody td {
            word-break: break-word;
            vertical-align: top;
        }

    </style>
@endpush

@section('title', 'Maths 300')

@section('content_header')
    <h1>
        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="{{ route('admin.forums.index') }}">Forums</a></li>
    </ol>
@stop

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <div class="col-md-8">
                <h3 class="box-title">Forums</h3>
            </div>
            <div class="col-md-4 text-right">
                <a href="{{ route('admin.forums.create') }}" class="btn btn-primary btn-flat">Add Forum</a>
            </div>

        </div>
        <!-- /.box-header -->

        <div class="box-body">
            <form id="schoolSearchForm" role="form" method="get" action="{{ route('admin.forums.index') }}">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-xs-6">
                        <div class="input-group">
                            <input type="text" class="form-control" id="q" name="q"
                                   placeholder="Enter forum keywords ..."
                                   value="{{ old('q') }}">
                            <span class="input-group-btn">
                                <button id="schoolSearchBtn" type="submit" class="btn btn-primary btn-flat ladda-button"
                                        data-style="expand-right"><span class="ladda-label">Search</span></button>
                            </span>
                        </div>
                    </div>
                </div><!-- /.row -->
            </form>
            <table id="tab_forums" class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Topics</th>
                    <th>Replies</th>
                    <th>Status</th>
                    <th>Menu</th>
                </tr>
                {{ csrf_field() }}
                </thead>
                <tbody>
                @foreach($forums as $l)
                    <tr class="item{{ $l->id }}">
                        <td><a href='{{ route('admin.forums.show',$l->id) }}'>{{ $l->title }}</a></td>
                        <td>{{ $l->getTopicsCount() }}</td>
                        <td>{{ $l->getRepliesCount() }}</td>
                        <td>{{ $l->getStatus() }}</td>
                        <td>
                            <a href="{{ route('admin.forums.edit',$l->id) }}" class="btn btn-primary">Edit</a>
                            <button class="delete-modal btn btn-danger" data-id="{{ $l->id }}"
                                    data-name="{{ $l->title }}">Delete
                            </button>

                            <div class="btn-group">
                                <button type="button" class="btn btn-warning">Change Status</button>
                                <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <span class="caret"></span>
                                    <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    @if( $l->isOpenAllowed() )
                                    <li>
                                        <a href="{{ route('admin.forums.open') }}" onclick="event.preventDefault();document.getElementById('open-form{{ $l->id }}').submit();">
                                            Open
                                        </a>
                                    </li>
                                    @endif

                                    @if( $l->isCloseAllowed() )
                                    <li>
                                        <a href="{{ route('admin.forums.close') }}" onclick="event.preventDefault();document.getElementById('close-form{{ $l->id }}').submit();">
                                            Close
                                        </a>
                                    </li>
                                    @endif
                                </ul>

                                <form id="open-form{{ $l->id }}" action="{{ route('admin.forums.open') }}" method="POST" style="display: none;">
                                    @csrf
                                    <input type="hidden" name="id_open" value="{{ $l->id }}">
                                </form>

                                <form id="close-form{{ $l->id }}" action="{{ route('admin.forums.close') }}" method="POST" style="display: none;">
                                    @csrf
                                    <input type="hidden" name="id_close" value="{{ $l->id }}">
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->

    @modal(['action' => 'delete', 'model' => 'forum'])
    @endmodal
@stop

@push('js')
    <!-- DataTables -->
    <script src="{{ asset('vendor/adminlte/vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/adminlte/vendor/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <!-- Select2 -->
    <script src="{{ asset ('vendor/adminlte/vendor/select2/dist/js/select2.full.min.js')}}"></script>

    <!-- icheck checkboxes -->
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#tab_forums').DataTable({
                "processing": true,
                'paging': true,
                'lengthChange': false,
                'searching': true,
                'language': {
                    'searchPlaceholder': "Search forums......"
                },
                'ordering': true,
                'info': true,
                'columnDefs': [
                    {
                        "searchable": false,
                        "orderable": false,
                        "targets": 4
                    }],
                'autoWidth': false,
                'columns': [{
                    "width": "40%"
                }, {
                    "width": "10%"
                }, {
                    "width": "10%"
                }, {
                    "width": "10%"
                }, {
                    "width": "30%"
                }
                ]
            });

            $(".dataTables_filter").hide();
        });

        // Automatically trigger the loading animation on click
        Ladda.bind('button[type=submit]');
    </script>

    @modaljs(['action' => 'delete', 'tab' => 'tab_forums', 'submit_url' => 'admin/forums'])
    @endmodaljs
@endpush