routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('/file/{filename}', 'FileController@getFile')->where('filename', '^(.+)\/([^\/]+)$')->name('getFile');

Auth::routes();

Route::namespace('Admin')->prefix('admin')->as('admin.')->middleware('auth')->middleware('role:super-admin')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::post('/lessons/publish', 'LessonController@publish')->name('lessons.publish');
    Route::post('/lessons/suspend', 'LessonController@suspend')->name('lessons.suspend');
    Route::get('/lessons/preview/{id}', 'LessonController@preview')->name('lessons.preview');
    Route::resource('/lessons', 'LessonController');

    Route::post('/schools/activate', 'SchoolController@activate')->name('schools.activate');
    Route::post('/schools/suspend', 'SchoolController@suspend')->name('schools.suspend');
    Route::post('/schools/archive', 'SchoolController@archive')->name('schools.archive');
    Route::post('/schools/reinstate', 'SchoolController@reinstate')->name('schools.reinstate');
    Route::get('/schools/showArchived', 'SchoolController@showArchived')->name('schools.showArchived');
    Route::post('/schools/setExpiryDate', 'SchoolController@setExpiryDate')->name('schools.setExpiryDate');
    Route::get('/schools/viewInvoice/{schoolID}', 'SchoolController@viewInvoice')->name('schools.viewInvoice');
    Route::resource('/schools', 'SchoolController');

    Route::post('/invoices/paid', 'InvoiceController@paid')->name('invoices.paid');
    Route::post('/invoices/send', 'InvoiceController@send')->name('invoices.send');
    Route::post('/invoices/cancel', 'InvoiceController@cancel')->name('invoices.cancel');
    Route::get('/invoices/showArchived', 'InvoiceController@showArchived')->name('invoices.showArchived');
    Route::get('/invoices/download/{invoice}', 'InvoiceController@download')->name('invoices.download');
    Route::get('/invoices/sendReminder/{invoice}', 'InvoiceController@sendReminder')->name('invoices.sendReminder');
    Route::post('/invoices/downloadXeroInvoice', 'InvoiceController@downloadXeroInvoice')->name('invoices.downloadXeroInvoice');
    Route::post('/invoices/adhocStore', 'InvoiceController@adhocStore')->name('invoices.adhocStore');
    Route::resource('/invoices', 'InvoiceController');
    

    Route::get('/resources/files', 'ResourceController@listFiles')->name('resources.listFiles');
    Route::get('/resources/images', 'ResourceController@listImages')->name('resources.listImages');
    Route::resource('/resources', 'ResourceController');

    Route::post('/users/activate', 'UserController@activate')->name('users.activate');
    Route::post('/users/suspend', 'UserController@suspend')->name('users.suspend');
    Route::post('/users/archive', 'UserController@archive')->name('users.archive');
    Route::post('/users/reinstate', 'UserController@reinstate')->name('users.reinstate');
    Route::get('/users/showArchived', 'UserController@showArchived')->name('users.showArchived');
    Route::post('/users/sendResetLinkEmail', 'UserController@sendResetLinkEmail')->name('users.sendResetLinkEmail');
    Route::post('/users/sendResetPassEmail', 'UserController@sendResetPassEmail')->name('users.sendResetPassEmail');
    Route::get('/users/changePassReq', 'UserController@changePassReq')->name('users.changePassReq');
    Route::post('/users/changePassword', 'UserController@changePassword')->name('users.changePassword');
    Route::resource('/users', 'UserController');

    Route::get('/reports/users', 'ReportsController@userindex')->name('reports.userindex');
    Route::get('/reports/schools', 'ReportsController@schoolindex')->name('reports.schoolindex');
    Route::get('/reports/invoices', 'ReportsController@invoiceindex')->name('reports.invoiceindex');
    Route::post('/reports/getusers', 'ReportsController@getusers')->name('reports.getusers');
    Route::post('/reports/getschools', 'ReportsController@getschools')->name('reports.getschools');
    Route::post('/reports/getinvoices', 'ReportsController@getinvoices')->name('reports.getinvoices');
    /* 
 * We name this route xero.auth.success as by default the config looks for a route with this name to redirect back to
 * after authentication has succeeded. The name of this route can be changed in the config file.
 */
    Route::get('/manage/xero', 'XeroController@index')->name('xero.auth.success');

    Route::post('/forums/open', 'ForumController@open')->name('forums.open');
    Route::post('/forums/close', 'ForumController@close')->name('forums.close');
    Route::resource('/forums', 'ForumController');

    Route::post('/topics/open', 'TopicController@open')->name('topics.open');
    Route::post('/topics/close', 'TopicController@close')->name('topics.close');
    Route::resource('/topics', 'TopicController');

    Route::resource('/replies', 'ReplyController');

    Route::resource('/yearlevels', 'YearLevelController');
    Route::resource('/contentstrands', 'ContentStrandController');
    Route::resource('/pedagogies', 'PedagogyController');
    Route::resource('/curricula', 'CurriculumController');
    Route::resource('/schooltypes', 'SchoolTypeController');
    Route::resource('/schoolsectors', 'SchoolSectorController');
    Route::resource('/schoolsizestudents', 'SchoolSizeStudentController');
    Route::resource('/schoolsizeteachers', 'SchoolSizeTeacherController');
    Route::get('/subscriptionplans/select/{school_size_id}', 'SubscriptionPlanController@select')->name('subscriptionplans.select');
    Route::resource('/subscriptionplans', 'SubscriptionPlanController');
    Route::resource('/countries', 'CountryController');
    Route::resource('/locations', 'LocationController');
    Route::resource('/discounts', 'DiscountController');

    Route::resource('/subscriptionpage', 'SubscriptionPageController');
    Route::resource('/aboutpage', 'AboutPageController');

    Route::post('/advertisements/publish', 'AdvertisementController@publish')->name('advertisements.publish');
    Route::post('/advertisements/suspend', 'AdvertisementController@suspend')->name('advertisements.suspend');
    Route::resource('/advertisements', 'AdvertisementController');

    Route::resource('/settings', 'SettingController');
    Route::resource('/faqpage', 'FAQPageController');
    //for tags
    Route::resource('/tags', 'TagController');
});

Route::namespace('Front')->as('front.')->group(function () {
    Route::get('/lessons/sample/{id}', 'LessonController@sample')->name('lessons.sample');
    Route::get('/lessons/listall', 'LessonController@listall')->name('lessons.listall');
    Route::post('/lessons/setAccessCode', 'LessonController@setAccessCode')->name('lessons.setAccessCode');

    Route::resource('/lessons', 'LessonController');
    //Route::resource('/faq', 'FAQController');
    Route::resource('/forums', 'ForumController');
    Route::resource('/topics', 'TopicController');
    Route::resource('/replies', 'ReplyController');
    Route::resource('/ads', 'AdvertisementController');

    Route::get('/contact', 'ContactController@index');
    Route::get('/about', 'AboutPageController@index')->name('about');
    Route::get('/subscribe', 'SubscriptionPageController@index')->name('subscription.index');
    Route::get('/terms/{hasAction}', 'SubscriptionPageController@termsAndConditions')->name('subscription.termsAndConditions');
    Route::get('/subscribe/create', 'SubscriptionPageController@create')->name('subscription.create');
    Route::post('/subscribe/store', 'SubscriptionPageController@store')->name('subscription.store');
    Route::get('/subscribe/notice', 'SubscriptionPageController@notice')->name('subscription.notice');
    Route::get('/subscribe/select/{school_size_id}', 'SubscriptionPageController@select')->name('subscription.select');

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/faq', 'FAQPageController@index')->name('faq');


    Route::post('/users/activate', 'UserController@activate')->name('users.activate');
    Route::post('/users/suspend', 'UserController@suspend')->name('users.suspend');
    Route::post('/users/archive', 'UserController@archive')->name('users.archive');
    Route::post('/users/reinstate', 'UserController@reinstate')->name('users.reinstate');
    Route::get('/users/showArchived', 'UserController@showArchived')->name('users.showArchived');
    Route::post('/users/sendResetLinkEmail', 'UserController@sendResetLinkEmail')->name('users.sendResetLinkEmail');
    Route::post('/users/sendResetPassEmail', 'UserController@sendResetPassEmail')->name('users.sendResetPassEmail');
    Route::get('/users/changePassReq', 'UserController@changePassReq')->name('users.changePassReq');
    Route::post('/users/changePassword', 'UserController@changePassword')->name('users.changePassword');
    Route::post('/users/addfavlesson', 'UserController@addfavlesson')->name('users.addfavlesson');
    Route::post('/users/removefavlesson', 'UserController@removefavlesson')->name('users.removefavlesson');
    Route::get('/users/listfavlessons', 'UserController@listfavlessons')->name('users.listfavlessons');
    Route::get('/users/invoices', 'UserController@invoices')->name('users.invoices');
    Route::get('/users/showInvoice/{invoice}', 'UserController@showInvoice')->name('users.showInvoice');
    Route::get('/users/downloadInvoice/{invoice}', 'UserController@downloadInvoice')->name('users.downloadInvoice');
    Route::resource('/users', 'UserController');
});

app/Models/YearLevel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class YearLevel extends Model
{
    /**
     * The lessons that belong to the year level.
     */
    public function lessons()
    {
        return $this->belongsToMany(Lesson::class);
    }

    /**
     * The users that belong to the year level.
     */
    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    /**
     * Scope a query to only include given keywords.
     *  query from name
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param  $keywords
     */
    public function scopeKeyWords($query, $keywords)
    {
        if ($keywords) $query->where('name', 'like', '%' . $keywords . '%');
    }
}

app/Http/Controllers/Admin/YearLevelController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\YearLevel;
use Illuminate\Http\Request;
use App\Http\Requests\YearLevelRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;
use Auth;
use Validator;

class YearLevelController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = YearLevel::query();
        if ($request->has('q') && $request->q != null) {
            // record user input keywords for further analysis in the future
            Log::info("search_keyword: " . $request->q);
            $query->keyWords($request->q);
        }

        $arr['yearlevels'] = $query->get();

        // allow using Input::old() function in view to access the data.
        $request->flash();

        return view('admin.yearlevels.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.yearlevels.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\YearLevelRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(YearLevelRequest $request)
    {
        // Retrieve the validated input data...
        $validated = $request->validated();

        $yearlevel = new YearLevel();
        $yearlevel->name = $validated['name'];

        $yearlevel->save();

        $request->session()->flash('alert-success', 'Year level added successfully.');

        return redirect()->route('admin.yearlevels.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\YearLevel $yearlevel
     * @return \Illuminate\Http\Response
     */
    public function show(YearLevel $yearlevel)
    {
        $arr['yearlevel'] = $yearlevel;

        return view('admin.yearlevels.show')->with($arr);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\YearLevel $yearLevel
     * @return \Illuminate\Http\Response
     */
    public function edit(YearLevel $yearlevel)
    {
        $arr['yearlevel'] = $yearlevel;
        return view('admin.yearlevels.edit')->with($arr);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\YearLevelRequest $request
     * @param  \App\Models\YearLevel $yearlevel
     * @return \Illuminate\Http\Response
     */
    public function update(YearLevelRequest $request, YearLevel $yearlevel)
    {
        // Retrieve the validated input data...
        $validated = $request->validated();

        $yearlevel->name = $validated['name'];

        $yearlevel->save();

        $request->session()->flash('alert-success', 'Year level updated successfully.');

        return redirect()->route('admin.yearlevels.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $yearlevel = YearLevel::findOrFail($id);
        Log::info("delete yearlevel " . $id);
        
        $yearlevel->delete();

        return response()->json($yearlevel);
    }
}

resources/views/admin/yearlevels/create.blade.php
@extends('adminlte::page')

@push('css')
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset ('vendor/adminlte/vendor/select2/dist/css/select2.min.css')}}">
@endpush

@section('title', 'Maths 300')

@section('content_header')
    <h1>
        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="{{ route('admin.yearlevels.index') }}">Year Levels</a></li>
    </ol>
@stop

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Add Year Level</h3>
        </div>
        <!-- /.box-header -->

        <div class="box-body">
            @if(count($errors))
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.
                    <br/>
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
        @endif
        <!-- form start -->
            <form id="yearlevelForm" role="form" method="post" action="{{ route('admin.yearlevels.store') }}">
                @csrf
                <div class="box-body">
                    <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" name="name"
                                  value="{{ old('name') }}">  
                        <span class="text-danger">{{ $errors->first('name') }}</span>
                    </div>
                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary ladda-button" data-style="expand-right"><span
                                class="ladda-label">Submit</span></button>
                </div>
            </form>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@stop

@push('js')
    <!-- Select2 -->
    <script src="{{ asset ('vendor/adminlte/vendor/select2/dist/js/select2.full.min.js')}}"></script>
    <!-- icheck checkboxes -->
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script>
        $(document).ready(function () {
            // Automatically trigger the loading animation on click
            Ladda.bind('button[type=submit]');
        });
    </script>
@endpush

resources/views/admin/yearlevels/edit.blade.php
@extends('adminlte::page')

@push('css')
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset ('vendor/adminlte/vendor/select2/dist/css/select2.min.css')}}">
@endpush

@section('title', 'Maths 300')

@section('content_header')
    <h1>
        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="{{ route('admin.yearlevels.index') }}">Year Levels</a></li>
    </ol>
@stop

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Edit Year Level</h3>
        </div>
        <!-- /.box-header -->

        <div class="box-body">
            @if(count($errors))
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.
                    <br/>
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
        @endif
        <!-- form start -->
                <form id="yearlevelForm" role="form" method="post" action="{{ route('admin.yearlevels.update', $yearlevel->id) }}">
                    @method('PUT')
                    @csrf
                <div class="box-body">
                    <input type="hidden" id="id" name="id" value="{{ old('id', $yearlevel->id) }}">
                    <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" name="name"
                                  value="{{ old('name', $yearlevel->name) }}">  
                        <span class="text-danger">{{ $errors->first('name') }}</span>
                    </div>
                </div>
                <!-- /.box-body -->

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary ladda-button" data-style="expand-right"><span
                                class="ladda-label">Submit</span></button>
                </div>
            </form>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@stop

@push('js')
    <!-- Select2 -->
    <script src="{{ asset ('vendor/adminlte/vendor/select2/dist/js/select2.full.min.js')}}"></script>
    <!-- icheck checkboxes -->
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script>
        $(document).ready(function () {
            // Automatically trigger the loading animation on click
            Ladda.bind('button[type=submit]');
        });
    </script>
@endpush

resources/views/admin/yearlevels/index.blade.php
@extends('adminlte::page')

@push('css')
    <!-- DataTables -->
    <link rel="stylesheet"
          href="{{ asset('vendor/adminlte/vendor/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
    <!-- Select2 -->
    <link rel="stylesheet" href="{{ asset ('vendor/adminlte/vendor/select2/dist/css/select2.min.css')}}">

    <style>
        table.dataTable tbody td {
            word-break: break-word;
            vertical-align: top;
        }

    </style>
@endpush

@section('title', 'Maths 300')

@section('content_header')
    <h1>
        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="{{ route('admin.yearlevels.index') }}">Year Levels</a></li>
    </ol>
@stop

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <div class="col-md-8">
                <h3 class="box-title">Year Levels</h3>
            </div>
            <div class="col-md-4 text-right">
                <a href="{{ route('admin.yearlevels.create') }}" class="btn btn-primary btn-flat">Add New</a>
            </div>

        </div>
        <!-- /.box-header -->

        <div class="box-body">
            <form id="yearlevelSearchForm" role="form" method="get" action="{{ route('admin.yearlevels.index') }}">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-xs-6">
                        <div class="input-group">
                            <input type="text" class="form-control" id="q" name="q"
                                   placeholder="Enter keywords..." value="{{ old('q') }}">
                            <span class="input-group-btn">
                                <button id="postSearchBtn" type="submit" class="btn btn-primary btn-flat ladda-button"
                                        data-style="expand-right"><span class="ladda-label">Search</span></button>
                            </span>
                        </div>
                    </div>
                </div>
            </form>
            <table id="tab_yearlevels" class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Menu</th>
                </tr>
                </thead>
                <tbody>
                @foreach($yearlevels as $l)
                    <tr class="item{{ $l->id }}">
                        <td></td>
                        <td><a href='{{ route('admin.yearlevels.show',$l->id) }}'>{{ $l->name }}</a></td>
                        <td>
                            <a href="{{ route('admin.yearlevels.edit', $l->id) }}" class="btn btn-primary">Edit</a>
                            <button class="delete-modal btn btn-danger" data-id="{{ $l->id }}"
                                    data-name="{{ $l->name }}">Delete
                            </button>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->

    @modal(['action' => 'delete', 'model' => 'yearlevel'])
    @endmodal
@stop

@push('js')
    <!-- DataTables -->
    <script src="{{ asset('vendor/adminlte/vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/adminlte/vendor/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <!-- Select2 -->
    <script src="{{ asset ('vendor/adminlte/vendor/select2/dist/js/select2.full.min.js')}}"></script>

    <!-- icheck checkboxes -->
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script>
        $(document).ready(function () {

            let t = $('#tab_yearlevels').DataTable({
                "processing": true,
                'paging': true,
                'lengthChange': false,
                'searching': true,
                'language': {
                    'searchPlaceholder': "Search yearlevels......"
                },
                'ordering': true,
                'info': true,
                'columnDefs': [
                    {
                        "searchable": false,
                        "orderable": false,
                        "targets": 0
                    },
                    {
                        "searchable": false,
                        "orderable": false,
                        "targets": 2
                    }
                ],
                'autoWidth': false,
                'columns': [{
                    "width": "10%"
                    },{
                    "width": "45%"
                    },{
                    "width": "45%"
                    }
                ]
            });

            $(".dataTables_filter").hide();

            t.on( 'order.dt search.dt', function () {
                t.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
                    cell.innerHTML = i+1;
                } );
            } ).draw();
        });

        // Automatically trigger the loading animation on click
        Ladda.bind('button[type=submit]');
    </script>

    @modaljs(['action' => 'delete', 'tab' => 'tab_yearlevels', 'submit_url' => 'admin/yearlevels'])
    @endmodaljs
@endpush

resources/views/admin/yearlevels/show.blade.php
@extends('adminlte::page')

@push('css')
@endpush

@section('title', 'Maths 300')

@section('content_header')
    <h1>
        <small></small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('admin.home') }}"><i class="fa fa-dashboard"></i>Home</a></li>
        <li><a href="{{ route('admin.yearlevels.index') }}">Year Levels</a></li>
    </ol>
@stop

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Year Level Details</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <h4>Name</h4>
            {{ $yearlevel->name }}
            <hr>

            <h4>Updated at</h4>
            {{ $yearlevel->updated_at }}
            <hr>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <a href="{{ route('admin.yearlevels.index') }}" class="btn btn-primary">Back</a>
        </div>
    </div>
    <!-- /.box -->
@stop

@push('js')
@endpush